version: '3.1'
services:
  ogame:
    container_name: ogame
    build: .
    environment:
      - OGAMED_UNIVERSE=${OGAMED_UNIVERSE}
      - OGAMED_USERNAME=${OGAMED_USERNAME}
      - OGAMED_PASSWORD=${OGAMED_PASSWORD}
      - OGAMED_LANGUAGE=${OGAMED_LANGUAGE}
      - OGAMED_HOST=${OGAMED_HOST}
      - OGAMED_PORT=${OGAMED_PORT}
      - OGAMED_AUTO_LOGIN=${OGAMED_AUTO_LOGIN}
      - OGAMED_PROXY=${OGAMED_PROXY}
      - OGAMED_PROXY_USERNAME=${OGAMED_PROXY_USERNAME}
      - OGAMED_PROXY_PASSWORD=${OGAMED_PROXY_PASSWORD}
      - OGAMED_PROXY_TYPE=${OGAMED_PROXY_TYPE}
      - OGAMED_PROXY_LOGIN_ONLY=${OGAMED_PROXY_LOGIN_ONLY}
      - OGAMED_NEW_HOSTNAME=${OGAMED_NEW_HOSTNAME}
      - OGAMED_AUTH_USERNAME=${OGAMED_AUTH_USERNAME}
      - OGAMED_AUTH_PASSWORD=${OGAMED_AUTH_PASSWORD}
      - OGAMED_ENABLE_TLS=${OGAMED_ENABLE_TLS}
      - OGAMED_TLS_CERTFILE=${OGAMED_TLS_CERTFILE}
      - OGAMED_TLS_KEYFILE=${OGAMED_TLS_KEYFILE}
      - OGAMED_COOKIES_FILENAME=${OGAMED_COOKIES_FILENAME}
      - CORS_ENABLED=${CORS_ENABLED}
    ports:
      - "127.0.0.1:8080:8080"