FROM golang:latest

ENV OGAMED_UNIVERSE=Bellatrix
ENV OGAMED_USERNAME=email@gmail.com
ENV OGAMED_PASSWORD=*****
ENV OGAMED_LANGUAGE=en
ENV OGAMED_HOST=0.0.0.0
ENV OGAMED_PORT=8080
ENV OGAMED_AUTO_LOGIN=true
ENV OGAMED_PROXY=
ENV OGAMED_PROXY_USERNAME=
ENV OGAMED_PROXY_PASSWORD=
ENV OGAMED_PROXY_TYPE=socks5
ENV OGAMED_PROXY_LOGIN_ONLY=false
ENV OGAMED_PROXY_PASSWORD=lobby
ENV OGAMED_NEW_HOSTNAME=http://0.0.0.0:8080
ENV OGAMED_AUTH_USERNAME=
ENV OGAMED_AUTH_PASSWORD=
ENV OGAMED_ENABLE_TLS=false
ENV OGAMED_TLS_CERTFILE=~/.ogame/key.pem
ENV OGAMED_TLS_KEYFILE=~/.ogame/cert.pem
ENV OGAMED_COOKIES_FILENAME=
ENV CORS_ENABLED=true

RUN mkdir -p /app
ADD . /app

WORKDIR /app
RUN go mod vendor

EXPOSE 8080

CMD ["go", "run", "./cmd/ogamed/main.go"]