package ogame

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestParseInt(t *testing.T) {
	assert.Equal(t, int64(1234567890), ParseInt("1.234.567.890"))
}

func TestToInt(t *testing.T) {
	assert.Equal(t, 1234567890, toInt([]byte("1234567890")))
}

func TestMinInt(t *testing.T) {
	assert.Equal(t, int64(2), MinInt(5, 2, 3))
}

func TestParseCoord(t *testing.T) {
	coord, _ := ParseCoord("[P:1:2:3]")
	assert.Equal(t, Coordinate{1, 2, 3, PlanetType}, coord)
	coord, _ = ParseCoord("[M:1:2:3]")
	assert.Equal(t, Coordinate{1, 2, 3, MoonType}, coord)
	coord, _ = ParseCoord("M:1:2:3")
	assert.Equal(t, Coordinate{1, 2, 3, MoonType}, coord)
	coord, _ = ParseCoord("1:2:3")
	assert.Equal(t, Coordinate{1, 2, 3, PlanetType}, coord)
	coord, _ = ParseCoord("1:2:3")
	assert.Equal(t, Coordinate{1, 2, 3, PlanetType}, coord)
	coord, _ = ParseCoord("D:1:2:3")
	assert.Equal(t, Coordinate{1, 2, 3, DebrisType}, coord)
	coord, _ = ParseCoord("[D:1:2:3]")
	assert.Equal(t, Coordinate{1, 2, 3, DebrisType}, coord)
	_, err := ParseCoord("[A:1:2:3]")
	assert.NotNil(t, err)
	_, err = ParseCoord("aP:1:2:3")
	assert.NotNil(t, err)
	_, err = ParseCoord("P:1234:2:3")
	assert.NotNil(t, err)
	_, err = ParseCoord("P:1:2345:3")
	assert.NotNil(t, err)
	_, err = ParseCoord("P:1:2:3456")
	assert.NotNil(t, err)
}

func TestName2id(t *testing.T) {
	assert.Equal(t, ID(0), name2id("Not valid"))
	assert.Equal(t, LightFighterID, name2id("Light Fighter"))
	assert.Equal(t, LightFighterID, name2id("Chasseur léger"))
	assert.Equal(t, LightFighterID, name2id("Leichter Jäger"))
	assert.Equal(t, LightFighterID, name2id("Caça Ligeiro"))
	assert.Equal(t, HeavyFighterID, name2id("Caça Pesado"))
	assert.Equal(t, LargeCargoID, name2id("Großer Transporter"))
	assert.Equal(t, DestroyerID, name2id("Zerstörer"))
	assert.Equal(t, SmallCargoID, name2id("Nave pequeña de carga"))
	assert.Equal(t, SolarSatelliteID, name2id("Satélite solar"))
	assert.Equal(t, ID(0), name2id("人中位"))

	// ro
	assert.Equal(t, LightFighterID, name2id("Vanator usor"))
	assert.Equal(t, HeavyFighterID, name2id("Vanator greu"))
	assert.Equal(t, CruiserID, name2id("Crucisator"))
	assert.Equal(t, BattleshipID, name2id("Nava de razboi"))
	assert.Equal(t, BattlecruiserID, name2id("Interceptor"))
	assert.Equal(t, BomberID, name2id("Bombardier"))
	assert.Equal(t, DestroyerID, name2id("Distrugator"))
	assert.Equal(t, DeathstarID, name2id("RIP"))
	assert.Equal(t, SmallCargoID, name2id("Transportor mic"))
	assert.Equal(t, LargeCargoID, name2id("Transportor mare"))
	assert.Equal(t, ColonyShipID, name2id("Nava de Colonizare"))
	assert.Equal(t, RecyclerID, name2id("Reciclator"))
	assert.Equal(t, EspionageProbeID, name2id("Proba de spionaj"))
	assert.Equal(t, SolarSatelliteID, name2id("Satelit solar"))
	assert.Equal(t, CrawlerID, name2id("Crawler"))
	assert.Equal(t, ReaperID, name2id("Reaper"))
	assert.Equal(t, PathfinderID, name2id("Pathfinder"))

	// cz
	assert.Equal(t, LightFighterID, name2id("Lehký stíhač"))
	assert.Equal(t, HeavyFighterID, name2id("Těžký stíhač"))
	assert.Equal(t, CruiserID, name2id("Křižník"))
	assert.Equal(t, BattleshipID, name2id("Bitevní loď"))
	assert.Equal(t, BattlecruiserID, name2id("Bitevní křižník"))
	assert.Equal(t, BomberID, name2id("Bombardér"))
	assert.Equal(t, DestroyerID, name2id("Ničitel"))
	assert.Equal(t, DeathstarID, name2id("Hvězda smrti"))
	assert.Equal(t, SmallCargoID, name2id("Malý transportér"))
	assert.Equal(t, LargeCargoID, name2id("Velký transportér"))
	assert.Equal(t, ColonyShipID, name2id("Kolonizační loď"))
	assert.Equal(t, RecyclerID, name2id("Recyklátor"))
	assert.Equal(t, EspionageProbeID, name2id("Špionážní sonda"))
	assert.Equal(t, SolarSatelliteID, name2id("Solární satelit"))
	assert.Equal(t, CrawlerID, name2id("Crawler"))
	assert.Equal(t, ReaperID, name2id("Rozparovač"))
	assert.Equal(t, PathfinderID, name2id("Průzkumník"))

	// mx
	assert.Equal(t, LightFighterID, name2id("Cazador ligero"))
	assert.Equal(t, HeavyFighterID, name2id("Cazador pesado"))
	assert.Equal(t, CruiserID, name2id("Crucero"))
	assert.Equal(t, BattleshipID, name2id("Nave de batalla"))
	assert.Equal(t, BattlecruiserID, name2id("Acorazado"))
	assert.Equal(t, BomberID, name2id("Bombardero"))
	assert.Equal(t, DestroyerID, name2id("Destructor"))
	assert.Equal(t, DeathstarID, name2id("Estrella de la muerte"))
	assert.Equal(t, SmallCargoID, name2id("Nave pequeña de carga"))
	assert.Equal(t, LargeCargoID, name2id("Nave grande de carga"))
	assert.Equal(t, ColonyShipID, name2id("Nave de la colonia"))
	assert.Equal(t, RecyclerID, name2id("Reciclador"))
	assert.Equal(t, EspionageProbeID, name2id("Sonda de espionaje"))
	assert.Equal(t, SolarSatelliteID, name2id("Satélite solar"))
	assert.Equal(t, CrawlerID, name2id("Taladrador"))
	assert.Equal(t, ReaperID, name2id("Segador"))
	assert.Equal(t, PathfinderID, name2id("Explorador"))

	// hr
	assert.Equal(t, LightFighterID, name2id("Mali lovac"))
	assert.Equal(t, HeavyFighterID, name2id("Veliki lovac"))
	assert.Equal(t, CruiserID, name2id("Krstarica"))
	assert.Equal(t, BattleshipID, name2id("Borbeni brod"))
	assert.Equal(t, BattlecruiserID, name2id("Oklopna krstarica"))
	assert.Equal(t, BomberID, name2id("Bombarder"))
	assert.Equal(t, DestroyerID, name2id("Razarač"))
	assert.Equal(t, DeathstarID, name2id("Zvijezda smrti"))
	assert.Equal(t, SmallCargoID, name2id("Mali transporter"))
	assert.Equal(t, LargeCargoID, name2id("Veliki transporter"))
	assert.Equal(t, ColonyShipID, name2id("Kolonijalni brod"))
	assert.Equal(t, RecyclerID, name2id("Recikler"))
	assert.Equal(t, EspionageProbeID, name2id("Sonde za špijunažu"))
	assert.Equal(t, SolarSatelliteID, name2id("Solarni satelit"))
	assert.Equal(t, CrawlerID, name2id("Puzavac"))
	assert.Equal(t, ReaperID, name2id("Žetelac"))
	assert.Equal(t, PathfinderID, name2id("Krčilac"))

	// no
	assert.Equal(t, LightFighterID, name2id("Lett Jeger"))
	assert.Equal(t, HeavyFighterID, name2id("Tung Jeger"))
	assert.Equal(t, CruiserID, name2id("Krysser"))
	assert.Equal(t, BattleshipID, name2id("Slagskip"))
	assert.Equal(t, BattlecruiserID, name2id("Slagkrysser"))
	assert.Equal(t, BomberID, name2id("Bomber"))
	assert.Equal(t, DestroyerID, name2id("Destroyer"))
	assert.Equal(t, DeathstarID, name2id("Døds stjerne"))
	assert.Equal(t, SmallCargoID, name2id("Lite Lasteskip"))
	assert.Equal(t, LargeCargoID, name2id("Stort Lasteskip"))
	assert.Equal(t, ColonyShipID, name2id("Koloni Skip"))
	assert.Equal(t, RecyclerID, name2id("Resirkulerer"))
	assert.Equal(t, EspionageProbeID, name2id("Spionasjesonde"))
	assert.Equal(t, SolarSatelliteID, name2id("Solar Satelitt"))
	assert.Equal(t, CrawlerID, name2id("Crawler"))
	assert.Equal(t, ReaperID, name2id("Reaper"))
	assert.Equal(t, PathfinderID, name2id("Pathfinder"))

	// it
	assert.Equal(t, LightFighterID, name2id("Caccia Leggero"))
	assert.Equal(t, HeavyFighterID, name2id("Caccia Pesante"))
	assert.Equal(t, CruiserID, name2id("Incrociatore"))
	assert.Equal(t, BattleshipID, name2id("Nave da battaglia"))
	assert.Equal(t, BattlecruiserID, name2id("Incrociatore da Battaglia"))
	assert.Equal(t, BomberID, name2id("Bombardiere"))
	assert.Equal(t, DestroyerID, name2id("Corazzata"))
	assert.Equal(t, DeathstarID, name2id("Morte Nera"))
	assert.Equal(t, SmallCargoID, name2id("Cargo leggero"))
	assert.Equal(t, LargeCargoID, name2id("Cargo Pesante"))
	assert.Equal(t, ColonyShipID, name2id("Colonizzatrice"))
	assert.Equal(t, RecyclerID, name2id("Riciclatrici"))
	assert.Equal(t, EspionageProbeID, name2id("Sonda spia"))
	assert.Equal(t, SolarSatelliteID, name2id("Satellite Solare"))
	assert.Equal(t, CrawlerID, name2id("Crawler"))
	assert.Equal(t, ReaperID, name2id("Reaper"))
	assert.Equal(t, PathfinderID, name2id("Pathfinder"))

	// pl
	assert.Equal(t, LightFighterID, name2id("Lekki myśliwiec"))
	assert.Equal(t, HeavyFighterID, name2id("Ciężki myśliwiec"))
	assert.Equal(t, CruiserID, name2id("Krążownik"))
	assert.Equal(t, BattleshipID, name2id("Okręt wojenny"))
	assert.Equal(t, BattlecruiserID, name2id("Pancernik"))
	assert.Equal(t, BomberID, name2id("Bombowiec"))
	assert.Equal(t, DestroyerID, name2id("Niszczyciel"))
	assert.Equal(t, DeathstarID, name2id("Gwiazda Śmierci"))
	assert.Equal(t, SmallCargoID, name2id("Mały transporter"))
	assert.Equal(t, LargeCargoID, name2id("Duży transporter"))
	assert.Equal(t, ColonyShipID, name2id("Statek kolonizacyjny"))
	assert.Equal(t, RecyclerID, name2id("Recykler"))
	assert.Equal(t, EspionageProbeID, name2id("Sonda szpiegowska"))
	assert.Equal(t, SolarSatelliteID, name2id("Satelita słoneczny"))
	assert.Equal(t, CrawlerID, name2id("Pełzacz"))
	assert.Equal(t, ReaperID, name2id("Rozpruwacz"))
	assert.Equal(t, PathfinderID, name2id("Pionier"))

	// tr
	assert.Equal(t, LightFighterID, name2id("Hafif Avcı"))
	assert.Equal(t, HeavyFighterID, name2id("Ağır Avcı"))
	assert.Equal(t, CruiserID, name2id("Kruvazör Adet"))
	assert.Equal(t, BattleshipID, name2id("Komuta Gemisi"))
	assert.Equal(t, BattlecruiserID, name2id("Firkateyn"))
	assert.Equal(t, BomberID, name2id("Bombardıman Gemisi"))
	assert.Equal(t, DestroyerID, name2id("Muhrip"))
	assert.Equal(t, DeathstarID, name2id("Ölüm Yildizi"))
	assert.Equal(t, SmallCargoID, name2id("Küçük Nakliye Gemisi"))
	assert.Equal(t, LargeCargoID, name2id("Büyük Nakliye Gemisi"))
	assert.Equal(t, ColonyShipID, name2id("Koloni Gemisi"))
	assert.Equal(t, RecyclerID, name2id("Geri Dönüsümcü"))
	assert.Equal(t, EspionageProbeID, name2id("Casus Sondasi"))
	assert.Equal(t, SolarSatelliteID, name2id("Solar Uydu"))
	assert.Equal(t, CrawlerID, name2id("Paletli"))
	assert.Equal(t, ReaperID, name2id("Azrail"))
	assert.Equal(t, PathfinderID, name2id("Rehber"))

	// ar
	assert.Equal(t, LightFighterID, name2id("Cazador ligero"))
	assert.Equal(t, HeavyFighterID, name2id("Cazador pesado"))
	assert.Equal(t, CruiserID, name2id("Crucero"))
	assert.Equal(t, BattleshipID, name2id("Nave de batalla"))
	assert.Equal(t, BattlecruiserID, name2id("Acorazado"))
	assert.Equal(t, BomberID, name2id("Bombardero"))
	assert.Equal(t, DestroyerID, name2id("Destructor"))
	assert.Equal(t, DeathstarID, name2id("Estrella de la muerte"))
	assert.Equal(t, SmallCargoID, name2id("Nave pequeña de carga"))
	assert.Equal(t, LargeCargoID, name2id("Nave grande de carga"))
	assert.Equal(t, ColonyShipID, name2id("Nave colonizadora"))
	assert.Equal(t, RecyclerID, name2id("Reciclador"))
	assert.Equal(t, EspionageProbeID, name2id("Sonda de espionaje"))
	assert.Equal(t, SolarSatelliteID, name2id("Satélite solar"))
	assert.Equal(t, CrawlerID, name2id("Taladrador"))
	assert.Equal(t, ReaperID, name2id("Segador"))
	assert.Equal(t, PathfinderID, name2id("Explorador"))

	//pt
	assert.Equal(t, LightFighterID, name2id("Caça Ligeiro"))
	assert.Equal(t, HeavyFighterID, name2id("Caça Pesado"))
	assert.Equal(t, CruiserID, name2id("Cruzador"))
	assert.Equal(t, BattleshipID, name2id("Nave de Batalha"))
	assert.Equal(t, BattlecruiserID, name2id("Interceptor"))
	assert.Equal(t, BomberID, name2id("Bombardeiro"))
	assert.Equal(t, DestroyerID, name2id("Destruidor"))
	assert.Equal(t, DeathstarID, name2id("Estrela da Morte"))
	assert.Equal(t, SmallCargoID, name2id("Cargueiro Pequeno"))
	assert.Equal(t, LargeCargoID, name2id("Cargueiro Grande"))
	assert.Equal(t, ColonyShipID, name2id("Nave de Colonização"))
	assert.Equal(t, RecyclerID, name2id("Reciclador"))
	assert.Equal(t, EspionageProbeID, name2id("Sonda de Espionagem"))
	assert.Equal(t, SolarSatelliteID, name2id("Satélite Solar"))
	assert.Equal(t, CrawlerID, name2id("Rastejador"))
	assert.Equal(t, ReaperID, name2id("Ceifeira"))
	assert.Equal(t, PathfinderID, name2id("Exploradora"))

	//nl
	assert.Equal(t, LightFighterID, name2id("Licht gevechtsschip"))
	assert.Equal(t, HeavyFighterID, name2id("Zwaar gevechtsschip"))
	assert.Equal(t, CruiserID, name2id("Kruiser"))
	assert.Equal(t, BattleshipID, name2id("Slagschip"))
	assert.Equal(t, BattlecruiserID, name2id("Interceptor"))
	assert.Equal(t, BomberID, name2id("Bommenwerper"))
	assert.Equal(t, DestroyerID, name2id("Vernietiger"))
	assert.Equal(t, DeathstarID, name2id("Ster des Doods"))
	assert.Equal(t, SmallCargoID, name2id("Klein vrachtschip"))
	assert.Equal(t, LargeCargoID, name2id("Groot vrachtschip"))
	assert.Equal(t, ColonyShipID, name2id("Kolonisatieschip"))
	assert.Equal(t, RecyclerID, name2id("Recycler"))
	assert.Equal(t, EspionageProbeID, name2id("Spionagesonde"))
	assert.Equal(t, SolarSatelliteID, name2id("Zonne-energiesatelliet"))
	assert.Equal(t, CrawlerID, name2id("Kruiper"))
	assert.Equal(t, ReaperID, name2id("Hein"))
	assert.Equal(t, PathfinderID, name2id("Padvinder"))

	//dk
	assert.Equal(t, LightFighterID, name2id("Lille Jæger"))
	assert.Equal(t, HeavyFighterID, name2id("Stor Jæger"))
	assert.Equal(t, CruiserID, name2id("Krydser"))
	assert.Equal(t, BattleshipID, name2id("Slagskib"))
	assert.Equal(t, BattlecruiserID, name2id("Interceptor"))
	assert.Equal(t, BomberID, name2id("Bomber"))
	assert.Equal(t, DestroyerID, name2id("Destroyer"))
	assert.Equal(t, DeathstarID, name2id("Dødsstjerne"))
	assert.Equal(t, SmallCargoID, name2id("Lille Transporter"))
	assert.Equal(t, LargeCargoID, name2id("Stor Transporter"))
	assert.Equal(t, ColonyShipID, name2id("Koloniskib"))
	assert.Equal(t, RecyclerID, name2id("Recycler"))
	assert.Equal(t, EspionageProbeID, name2id("Spionagesonde"))
	assert.Equal(t, SolarSatelliteID, name2id("Solarsatellit"))
	assert.Equal(t, CrawlerID, name2id("Kravler"))
	assert.Equal(t, ReaperID, name2id("Reaper"))
	assert.Equal(t, PathfinderID, name2id("Stifinder"))

	// ru
	assert.Equal(t, LightFighterID, name2id("Лёгкий истребитель"))
	assert.Equal(t, HeavyFighterID, name2id("Тяжёлый истребитель"))
	assert.Equal(t, CruiserID, name2id("Крейсер"))
	assert.Equal(t, BattleshipID, name2id("Линкор"))
	assert.Equal(t, BattlecruiserID, name2id("Линейный крейсер"))
	assert.Equal(t, BomberID, name2id("Бомбардировщик"))
	assert.Equal(t, DestroyerID, name2id("Уничтожитель"))
	assert.Equal(t, DeathstarID, name2id("Звезда смерти"))
	assert.Equal(t, SmallCargoID, name2id("Малый транспорт"))
	assert.Equal(t, LargeCargoID, name2id("Большой транспорт"))
	assert.Equal(t, ColonyShipID, name2id("Колонизатор"))
	assert.Equal(t, RecyclerID, name2id("Переработчик"))
	assert.Equal(t, EspionageProbeID, name2id("Шпионский зонд"))
	assert.Equal(t, SolarSatelliteID, name2id("Солнечный спутник"))
	assert.Equal(t, CrawlerID, name2id("Гусеничник"))
	assert.Equal(t, ReaperID, name2id("Жнец"))
	assert.Equal(t, PathfinderID, name2id("Первопроходец"))

	// gr
	assert.Equal(t, LightFighterID, name2id("Ελαφρύ Μαχητικό"))
	assert.Equal(t, HeavyFighterID, name2id("Βαρύ Μαχητικό"))
	assert.Equal(t, CruiserID, name2id("Καταδιωκτικό"))
	assert.Equal(t, BattleshipID, name2id("Καταδρομικό"))
	assert.Equal(t, BattlecruiserID, name2id("Θωρηκτό Αναχαίτισης"))
	assert.Equal(t, BomberID, name2id("Βομβαρδιστικό"))
	assert.Equal(t, DestroyerID, name2id("Destroyer"))
	assert.Equal(t, DeathstarID, name2id("Deathstar"))
	assert.Equal(t, SmallCargoID, name2id("Μικρό Μεταγωγικό"))
	assert.Equal(t, LargeCargoID, name2id("Μεγάλο Μεταγωγικό"))
	assert.Equal(t, ColonyShipID, name2id("Σκάφος Αποικιοποίησης"))
	assert.Equal(t, RecyclerID, name2id("Ανακυκλωτής"))
	assert.Equal(t, EspionageProbeID, name2id("Κατασκοπευτικό Στέλεχος"))
	assert.Equal(t, SolarSatelliteID, name2id("Ηλιακοί Συλλέκτες"))
	assert.Equal(t, CrawlerID, name2id("Crawler"))
	assert.Equal(t, ReaperID, name2id("Reaper"))
	assert.Equal(t, PathfinderID, name2id("Pathfinder"))

	// jp
	assert.Equal(t, LightFighterID, name2id("軽戦闘機"))
	assert.Equal(t, HeavyFighterID, name2id("重戦闘機"))
	assert.Equal(t, CruiserID, name2id("巡洋艦"))
	assert.Equal(t, BattleshipID, name2id("バトルシップ"))
	assert.Equal(t, BattlecruiserID, name2id("大型戦艦"))
	assert.Equal(t, BomberID, name2id("爆撃機"))
	assert.Equal(t, DestroyerID, name2id("デストロイヤー"))
	assert.Equal(t, DeathstarID, name2id("デススター"))
	assert.Equal(t, SmallCargoID, name2id("小型輸送機"))
	assert.Equal(t, LargeCargoID, name2id("大型輸送機"))
	assert.Equal(t, ColonyShipID, name2id("コロニーシップ"))
	assert.Equal(t, RecyclerID, name2id("残骸回収船"))
	assert.Equal(t, EspionageProbeID, name2id("偵察機"))
	assert.Equal(t, SolarSatelliteID, name2id("ソーラーサテライト"))
	assert.Equal(t, CrawlerID, name2id("クローラー"))
	assert.Equal(t, ReaperID, name2id("リーパー"))
	assert.Equal(t, PathfinderID, name2id("パスファインダー"))

	// sk
	assert.Equal(t, LightFighterID, name2id("Ľahký stíhač"))
	assert.Equal(t, HeavyFighterID, name2id("Ťažký stíhač"))
	assert.Equal(t, CruiserID, name2id("Krížnik"))
	assert.Equal(t, BattleshipID, name2id("Bojová loď"))
	assert.Equal(t, BattlecruiserID, name2id("Bojový krížnik"))
	assert.Equal(t, BomberID, name2id("Bombardér"))
	assert.Equal(t, DestroyerID, name2id("Devastátor"))
	assert.Equal(t, DeathstarID, name2id("Hviezda smrti"))
	assert.Equal(t, SmallCargoID, name2id("Malý transportér"))
	assert.Equal(t, LargeCargoID, name2id("Veľký transportér"))
	assert.Equal(t, ColonyShipID, name2id("Kolonizačná loď"))
	assert.Equal(t, RecyclerID, name2id("Recyklátor"))
	assert.Equal(t, EspionageProbeID, name2id("Špionážna sonda"))
	assert.Equal(t, SolarSatelliteID, name2id("Solárny satelit"))
	assert.Equal(t, CrawlerID, name2id("Vrták"))
	assert.Equal(t, ReaperID, name2id("Kosa"))
	assert.Equal(t, PathfinderID, name2id("Prieskumník"))

	// si
	assert.Equal(t, LightFighterID, name2id("Lahek lovec"))
	assert.Equal(t, HeavyFighterID, name2id("Težki lovec"))
	assert.Equal(t, CruiserID, name2id("Križarka"))
	assert.Equal(t, BattleshipID, name2id("Bojna ladja"))
	assert.Equal(t, BattlecruiserID, name2id("Bojna križarka"))
	assert.Equal(t, BomberID, name2id("Bombnik"))
	assert.Equal(t, DestroyerID, name2id("Uničevalec"))
	assert.Equal(t, DeathstarID, name2id("Zvezda smrti"))
	assert.Equal(t, SmallCargoID, name2id("Majhna tovorna ladja"))
	assert.Equal(t, LargeCargoID, name2id("Velika tovorna ladja"))
	assert.Equal(t, ColonyShipID, name2id("Kolonizacijska ladja"))
	assert.Equal(t, RecyclerID, name2id("Recikler"))
	assert.Equal(t, EspionageProbeID, name2id("Vohunska sonda"))
	assert.Equal(t, SolarSatelliteID, name2id("Sončni satelit"))
	assert.Equal(t, CrawlerID, name2id("Plazilec"))
	assert.Equal(t, ReaperID, name2id("Kombajn"))
	assert.Equal(t, PathfinderID, name2id("Iskalec sledi"))

	// fr
	assert.Equal(t, LightFighterID, name2id("Chasseur léger"))
	assert.Equal(t, HeavyFighterID, name2id("Chasseur lourd"))
	assert.Equal(t, CruiserID, name2id("Croiseur"))
	assert.Equal(t, BattleshipID, name2id("Vaisseau de bataille"))
	assert.Equal(t, BattlecruiserID, name2id("Traqueur"))
	assert.Equal(t, BomberID, name2id("Bombardier"))
	assert.Equal(t, DestroyerID, name2id("Destructeur"))
	assert.Equal(t, DeathstarID, name2id("Étoile de la mort"))
	assert.Equal(t, SmallCargoID, name2id("Petit transporteur"))
	assert.Equal(t, LargeCargoID, name2id("Grand transporteur"))
	assert.Equal(t, ColonyShipID, name2id("Vaisseau de colonisation"))
	assert.Equal(t, RecyclerID, name2id("Recycleur"))
	assert.Equal(t, EspionageProbeID, name2id("Sonde d`espionnage"))
	assert.Equal(t, SolarSatelliteID, name2id("Satellite solaire"))
	assert.Equal(t, CrawlerID, name2id("Foreuse"))
	assert.Equal(t, ReaperID, name2id("Faucheur"))
	assert.Equal(t, PathfinderID, name2id("Éclaireur"))

	// tw
	assert.Equal(t, LightFighterID, name2id("輕型戰鬥機"))
	assert.Equal(t, HeavyFighterID, name2id("重型戰鬥機"))
	assert.Equal(t, CruiserID, name2id("巡洋艦"))
	assert.Equal(t, BattleshipID, name2id("戰列艦"))
	assert.Equal(t, BattlecruiserID, name2id("戰鬥巡洋艦"))
	assert.Equal(t, BomberID, name2id("導彈艦"))
	assert.Equal(t, DestroyerID, name2id("毀滅者"))
	assert.Equal(t, DeathstarID, name2id("死星"))
	assert.Equal(t, SmallCargoID, name2id("小型運輸艦"))
	assert.Equal(t, LargeCargoID, name2id("大型運輸艦"))
	assert.Equal(t, ColonyShipID, name2id("殖民船"))
	assert.Equal(t, RecyclerID, name2id("回收船"))
	assert.Equal(t, EspionageProbeID, name2id("間諜衛星"))
	assert.Equal(t, SolarSatelliteID, name2id("太陽能衛星"))
	assert.Equal(t, CrawlerID, name2id("履帶車"))
	assert.Equal(t, ReaperID, name2id("惡魔飛船"))
	assert.Equal(t, PathfinderID, name2id("探路者"))
}
